#!/bin/bash
# script to launch eclipse docker image

ECLIPSE_PLUGINS_DIR=.eclipse-docker
WORKDIR=`pwd`

if [ ! -d "$WORKDIR/$ECLIPSE_PLUGINS_DIR" ]; then
    mkdir $WORKDIR/$ECLIPSE_PLUGINS_DIR
    cat <<EOF > $WORKDIR/$ECLIPSE_PLUGINS_DIR/eclipse.ini
-startup
plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.300.v20150602-1417
-product
org.eclipse.epp.package.jee.product
--launcher.defaultAction
openFile
-showsplash
org.eclipse.platform
--launcher.XXMaxPermSize
256m
--launcher.defaultAction
openFile
--launcher.GTK_version
2
--launcher.appendVmargs
-vmargs
-Dosgi.requiredJavaVersion=1.7
-Xms512m
-Xmx4096m
EOF
fi

echo "Starting eclipse with workspace $WORKDIR"
docker run \
       --rm \
       -it \
       -e DISPLAY=$DISPLAY \
       -v /tmp/.X11-unix:/tmp/.X11-unix \
       -v $WORKDIR/$ECLIPSE_PLUGINS_DIR:/home/dev/.eclipse \
       -v $WORKDIR:/home/dev/workspace \
       gilesp/eclipse

